const ConstructorTest           = require("./tests/constructor");
const IntersectTest             = require("./tests/intersect");
const UnionTest                 = require("./tests/union");
const DifferenceTest            = require("./tests/difference");
const SymmetricDifferenceTest   = require("./tests/symmetric_difference");
const DistinctTest              = require("./tests/distinct");
const CountTest                 = require("./tests/count");
const FindIndicesTest           = require("./tests/find_indices");
const RangeTest                 = require("./tests/range");
const PadTest                   = require("./tests/pad");
const SumTest                   = require("./tests/sum");
const ProductTest               = require("./tests/product");
const RandomTest                = require("./tests/random");
const ShuffleTest               = require("./tests/shuffle");
const IsSortedTest              = require("./tests/is_sorted");
const BinarySearchTest          = require("./tests/binary_search");
const GenerateRandomTest        = require("./tests/generate_random");
const EqualsTest                = require("./tests/equals");
const MinTest                   = require("./tests/min");
const MaxTest                   = require("./tests/max");
const GetRangeTest              = require("./tests/get_range");
const GetMedianTest             = require("./tests/get_median");
const GetAverageTest            = require("./tests/get_average");
const AddTest                   = require("./tests/add");
const SubtractTest              = require("./tests/subtract");
const MultiplyTest              = require("./tests/multiply");
const DivideTest                = require("./tests/divide");
const ExponentTest              = require("./tests/exponent");

ConstructorTest();
IntersectTest();
UnionTest();
DifferenceTest();
SymmetricDifferenceTest();
DistinctTest();
CountTest();
FindIndicesTest();
RangeTest();
PadTest();
SumTest();
ProductTest();
RandomTest();
ShuffleTest();
IsSortedTest();
BinarySearchTest();
GenerateRandomTest();
EqualsTest();
MinTest();
MaxTest();
GetRangeTest();
GetMedianTest();
GetAverageTest();
AddTest();
SubtractTest();
MultiplyTest();
DivideTest();
ExponentTest();